FROM node:16-alpine as build
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN apk add --no-cache git
RUN yarn
COPY . .
RUN yarn run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html