version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - server
      - ml
    image: jmp119/nft-toolkit-nginx:latest
    restart: always
    ports:
      - "80:80"
  client:
    image: jmp119/nft-toolkit-client:latest
    restart: on-failure
  server:
    image: jmp119/nft-toolkit-server:latest
    deploy:
      resources:
        limits:
          cpus: "1.5"
    env_file:
      - .env
    restart: on-failure
  ml:
    image: jmp119/nft-toolkit-ml:latest
    restart: on-failure
    env_file:
      - .env
