version: "3"
services:
  client:
    stdin_open: true
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
