/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  ERC2981ContractWideRoyalties,
  ERC2981ContractWideRoyaltiesInterface,
} from "../ERC2981ContractWideRoyalties";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x57ec8f95",
        type: "bytes32",
      },
    ],
    name: "c_0x57ec8f95",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0xc4d48488",
        type: "bytes32",
      },
    ],
    name: "c_0xc4d48488",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "royaltyInfo",
    outputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "royaltyAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ERC2981ContractWideRoyalties__factory {
  static readonly abi = _abi;
  static createInterface(): ERC2981ContractWideRoyaltiesInterface {
    return new utils.Interface(_abi) as ERC2981ContractWideRoyaltiesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2981ContractWideRoyalties {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC2981ContractWideRoyalties;
  }
}
