// ANY CHANGES MADE HERE WILL AFFECT reducers/formReducer.ts
// UPDATE ACCORDINGLY

enum FormActions {
  // collection details
  CHANGE_NAME,
  CHANGE_PRICE,
  CHANGE_SYMBOL,
  CHANGE_DESCRIPTION,
  // image uploads
  ADD_IMAGES_STATIC,
  DELETE_IMAGE_STATIC,
  CHANGE_IMAGE_NAME,
  CHANGE_IMAGE_DESC,
  ADD_IMAGES_GEN,
  CHANGE_IMAGE_NAME_GEN,
  DELETE_IMAGE_GEN,
  // tiers
  ADD_TIER,
  REMOVE_TIER,
  CHANGE_TIER_PRECEDENCE,
  CHANGE_TIER_PROBABILITY,
  // layers
  ADD_LAYER,
  REMOVE_LAYER,
  CHANGE_RARITY,
  CHANGE_LAYER_PRECEDENCE,
  CHANGE_LAYER_PROBABILITY,
  CHANGE_QUANTITY,
  // resets
  RESET_STATE,
  // predictions
  CHANGE_PREDICTIONS,
  CHANGE_TWITTER_HANDLE,
  CHANGE_REDDIT_HANDLE,
  // marketplace
  CHANGE_WANTED,
  CHANGE_ROYALTY,
}

export default FormActions;
