enum FormActions {
  CHANGE_NAME,
  CHANGE_PRICE,
  CHANGE_SYMBOL,
  CHANGE_DESCRIPTION,
  RESET_STATE,
  CHANGE_IMAGES,
  CHANGE_IMAGE_NAME,
  DELETE_IMAGE,
  CHANGE_IMAGES_GEN,
  CHANGE_IMAGE_NAME_GEN,
  DELETE_IMAGE_GEN,
  ADD_LAYER,
  REMOVE_LAYER,
  CHANGE_PRECEDENCE,
  RESET_TYPE_OF_ART,
}

export default FormActions;
