# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Client CI

on:
  push:
    branches-ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Set-up seed env vars
      #   run: echo "REACT_APP_SEED=${{ secrets.SEED }}" >> client/.env
      - name: Install dependencies
        run: yarn && cd client/ && yarn
      - name: Build
        run: cd client/ && yarn build
      - name: Test
        run: cd client/ && yarn test --coverage
