name: Python CI

on:
  push:
    branches-ignore: []

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Format
        run: autopep8 -r --diff --exit-code .
      - name: Lint
        run: pylint $(find . -name "*.py" | xargs)
      - name: Commit Convention
        run: python3 git-hooks/commit_checker.py
      - name: ESLint disabled warnings
        run: python3 git-hooks/pre-push.py
      - name: Run pytest
        run: pytest
