# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    branches-ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn && cd server/ && yarn
      - name: TSC Build
        run: cd server/ && yarn build
      - name: Hardhat Build
        run: cd server/ && yarn compile
      - name: Test
        run: cd server/ && yarn test --ci
